VIA_ENABLE = yes
VIAL_ENABLE = yes

COMMAND_ENABLE = no

RGB_MATRIX_ENABLE = yes        # Use RGB matrix
CIE1931_CURVE = yes
VIALRGB_ENABLE = yes

QMK_SETTINGS = no
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no

VIAL_ENCODERS_ENABLE = yes
