#pragma once

#define VIAL_KEYBOARD_UID {0x8F, 0xE2, 0x0E, 0xC4, 0x79, 0x10, 0x54, 0x5F}


#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 5 }

#define VIAL_ENCODER_DEFAULT { \
    USER00, USER01, \
    KC_TRNS, KC_TRNS, \
    KC_TRNS, KC_TRNS, \
    KC_TRNS, KC_TRNS \
}

#define ENCODER_DIRECTION_FLIP

#define RAW_USAGE_PAGE 0xFF60
#define RAW_USAGE_ID 0x61
